[project]
name = "codebaseexplorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SergeyGushchin", email = "gushchins95@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "codebase-explorer-agent",
    "semantic-explorer",
]

[project.scripts]
codebaseexplorer = "codebase_explorer:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "codebase_explorer"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
    "pytest>=9.1.1",
]

[tool.pyright]
extraPaths = [
    "src",
    "packages/codebase_explorer_agent/src",
    "packages/semantic_explorer/src",
]

[tool.uv.sources]
codebase-explorer-agent = { workspace = true }
semantic-explorer = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/semantic_explorer",
    "packages/codebase_explorer_agent",
]
