[project]
name = "codebaseexplorer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SergeyGushchin", email = "gushchins95@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai-slim[openai]>=2.44.0",
    "pymonad>=2.4.0",
]

[project.scripts]
codebaseexplorer = "codebaseexplorer:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.414",
]
